<?php
$worker_images = array(
    "Angela_Zefi" => "images_converted/Angela_Zefi.jpg",
    "Anika_Bartholomeusz" => "images_converted/Anika_Bartholomeusz.jpg",
    "Benjamin (Ben) Roberts" => "images_converted/Benjamin (Ben) Roberts.jpg",
    "Bronte (Bunny) Pettman" => "images_converted/Bronte (Bunny) Pettman.jpg",
    "Chaynne_Humphrys" => "images_converted/Chaynne_Humphrys.jpg",
    "Chi_Ha" => "images_converted/Chi_Ha.jpg",
    "Courtney_Millington" => "images_converted/Courtney_Millington.jpg",
    "Dhara_Patel" => "images_converted/Dhara_Patel.jpg",
    "Dhruv_Sabharwal" => "images_converted/Dhruv_Sabharwal.jpg",
    "Fernando_Arnibar" => "images_converted/Fernando_Arnibar.jpg",
    "Gaumit_Patel" => "images_converted/Gaumit_Patel.jpg",
    "Harshkumar (Happy) Modi" => "images_converted/Harshkumar (Happy) Modi.jpg",
    "Japneet (Rosie) Kaur" => "images_converted/Japneet (Rosie) Kaur.jpg",
    "Jarryd_Humphrys" => "images_converted/Jarryd_Humphrys.jpg",
    "Joe_Zhang" => "images_converted/Joe_Zhang.jpg",
    "Joseph_Espejo" => "images_converted/Joseph_Espejo.jpg",
    "Jose_Diaz_Armijo" => "images_converted/Jose_Diaz_Armijo.jpg",
    "Julie_Moore" => "images_converted/Julie_Moore.jpg",
    "Kapil_Lamichane" => "images_converted/Kapil_Lamichane.jpg",
    "Margerite (Rita) Gjergji" => "images_converted/Margerite (Rita) Gjergji.jpg",
    "Marie (Maz) Andersen" => "images_converted/Marie (Maz) Andersen.jpg",
    "Meena_Sapkota" => "images_converted/Meena_Sapkota.jpg",
    "Muhammad_Hamza" => "images_converted/Muhammad_Hamza.jpg",
    "Otto_Basson" => "images_converted/Otto_Basson.jpg",
    "Parvinder_Kaur" => "images_converted/Parvinder_Kaur.jpg",
    "Pranvera_Ymeraj" => "images_converted/Pranvera_Ymeraj.jpg",
    "Rita_Gjergji" => "images_converted/Rita_Gjergji.jpg",
    "Robandeep (Roban) Singh" => "images_converted/Robandeep (Roban) Singh.jpg",
    "Rodrigo_Tangol" => "images_converted/Rodrigo_Tangol.jpg",
    "Sandy_Tran" => "images_converted/Sandy_Tran.jpg",
    "Victoria_Horsfall" => "images_converted/Victoria_Horsfall.jpg"
);
?>
